# Generated by Django 4.2.4 on 2023-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spine', models.ImageField(upload_to='')),
                ('book', models.ImageField(upload_to='')),
                ('bottle', models.ImageField(upload_to='')),
                ('brunch', models.ImageField(upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('alcoholLevel', models.CharField(max_length=255)),
                ('flavor', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
